### ISSUE TITLE
firebase

### ISSUE THREAD

**Issue by swabzz** [FuckBoilerplate/base_app_ios#6]
Hi,

trying to add firebase but getting exception in pod installation may be due to CloudMessaging already integrated.

pod 'Firebase/Core'

Please suggest the solution. Thanks

**Comment by robertofrontado** [comment]
Hello @swabzz, are you still struggling with this?

In that case, you coud remove the `CloudMessaging` library and integrate `Firebase/Core`, then adjust manually the code (Using firebase instead of the old cloud messaging code)

If you need further help let me know!

Also you can add just what you need of [Firebase](https://firebase.google.com/docs/ios/setup#available_pods):

<img width="657" alt="screen shot 2017-07-05 at 11 05 48 am" src="https://user-images.githubusercontent.com/11177510/27857433-edd757b8-6171-11e7-8750-2b344747bca4.png">

**Comment by swabzz** [comment]
Thanks @robertofrontado for your reply.
I will check pod and let you know
